[package]
name = "rust-nbody"
version = "0.1.0"
authors = ["ischeinkman <scheinkman.ilan@gmail.com>"]
edition = "2018"

[dependencies]
rand= "0.6"

sdl2={version = "0.32", features = ["image", "unsafe_textures"] }